### ISSUE TITLE
LUA scripts that modify the resulting HTML, NCX, and OPF files (workaround with dom-filters?)

### ISSUE THREAD

**Issue by ClemensLode** [michal-h21/tex4ebook#101]
Short question: Where do I place (and how do I call) LUA scripts that modify the resulting HTML, NCX, and OPF files?

---

Long explanation: 

I am using tikzexternalize to generate JPG files out of my tikz graphics. This works quite well, but tex4ebook ignores any generated JPG files as they are not referenced directly in the LaTeX code. 

I am using this code:

```
\usetikzlibrary{external}
\tikzexternalize
\tikzset{jpg export/.style={external/system call={pdflatex \tikzexternalcheckshellescape -interaction=batchmode -jobname "\image" "\texsource"; convert -gravity center -extent 1245 -strip -quality 100 -density 300 -transparent white "\image.pdf" "\image.jpg"},/pgf/images/external info,/pgf/images/include external/.code=\includegraphics{##1.jpg}}}
\tikzset{jpg export}
\tikzsetexternalprefix{tikz-cache/} 

```

As a result, for each tikz picture, a JPG file is placed in the tikz-cache directory.

When using a simple call

`tex4ebook main`

both the OPF file and the HTML files reference the original `main?x.svg` instead of `tikz-cache/output-figure?.jpg`

What would be a workaround to make the necessary change to the OPF, NCX, and HTML files?

I understand that a LUA script like

```
return function(dom)
  for _,img in ipairs(dom:query_selector("img")) do
    if img:get_attribute("src"):match("svg$") then
      img:set_attribute("src","tikz-cache/output-figure" .. string.match(img:get_attribute("src"),"%d+") .. ".jpg")
    end
  end
  return dom
end
```

would do the job, but how do I call it as part as the build process?

I have read that `make4ht` supports domfilters, but I am not sure if tex4ebook does as well. Placing a `make4ht-htmlimg.lua` file into the `/domfilters` directory and calling it in `/main.mk4` does not seem to do the trick, but I am sure I have missed something...

```
Make:add("bibtex","bibtex ${input}")
Make:htlatex {}
Make:bibtex {}
Make:htlatex {}
Make:htlatex {}

local domfilters = require "make4ht-domfilter"
local process = domfilters {"htmlimg"}
Make:match("htm?$", process)
```

Any suggestion?

Thank you in advance!

**Comment by michal-h21** [comment]
Which TeX distro do you use? The following works for me with TeX Live 2022:

```
\documentclass{article}
\usepackage{tikz}
\usetikzlibrary{external}
\tikzexternalize
\tikzset{jpg export/.style={external/system call={pdflatex \tikzexternalcheckshellescape -interaction=batchmode -jobname "\image" "\texsource"; convert -gravity center -extent 1245 -strip -quality 100 -density 300 -transparent white "\image.pdf" "\image.jpg"},/pgf/images/external info,/pgf/images/include external/.code=\includegraphics{##1.jpg}}}
\tikzset{jpg export}
\tikzsetexternalprefix{tikz-cache/} 
\begin{document}

Hello:

\begin{tikzpicture}[sibling distance=10em,
  every node/.style = {shape=rectangle, rounded corners,
    draw, align=center,
    top color=white, bottom color=blue!20}]]
  \node {Formulas}
    child { node {single-line} }
    child { node {multi-line}
      child { node {aligned at}
        child { node {relation sign} }
        child { node {several places} }
        child { node {center} } }
      child { node {first left,\\centered,\\last right} } };
\end{tikzpicture}
\end{document}

```

In general, TeX4ht should detect that you use TikZ externalization and include the externalized picture. 

I would check if you don't have a older version of the [TeX4ht TikZ driver](https://github.com/michal-h21/dvisvgm4ht) somewhere on your system (you can find it's location using `kpsewhich pgfsys-dvisvgm4ht.def`), the older versions didn't support externalization.

**Comment by ClemensLode** [comment]
Hi! Thanks for the quick reply! 

Unfortunately, this has the same result.

- I am using Overleaf (`TexLive 2022`, I tried it both with `pdfLaTeX` and `XeLaTeX`)
- Here is a minimal working example: https://www.overleaf.com/4485879684mqfdzzsspnjx
  - You might have to clear the cache by clicking the "Logs and output files" icon and then pressing "Clear cached files" at the bottom.
- The code compiles, and produces a PDF and an EPUB, but the EPUB file itself contains only the generated SVG files, not the JPG files.
  - HTML file: `<img alt='' src='main0x.svg' />`
  - OPF file: `<item id="main0x_svg" href="main0x.svg" media-type="image/svg+xml"/>`
  - PGF version reports `3.1.9a`
    - The current version is `3.1.10' (`Fix for externalization and horizontal mode') but that's from just 2 weeks ago and probably not related (I haven't tried 3.1.10 yet, though, that would be a next step).

Thank you in advance.

**Comment by michal-h21** [comment]
Ah, I see a problem in the `latexmkrc` file. You deleted all files from `tikz-cache`, so `tex4ebook` couldn't insert the images. The other issue was that the TikZ driver that was used was wrong, so I uploaded the updated version. And the issue that took me the longest  time to debug is that Overleaf sets `-jobname` in the compilation, so the cached image is not named `main-....jpg`, but `output....jpg`, and `tex4ebook` couldn't find it, as it was looking for `main...jpg`. Fortunately, `tex4ebook` can change jobname too, it can find the file correctly.

**Comment by ClemensLode** [comment]
Ah... OK, that makes sense :) Thanks a lot! That saves me some time manually converting the files :)

**Comment by hendricius** [comment]
@ClemensLode what did you do in the end to make the images the proper size in the generated document? In the example you shared the resulting images are very big. Thank you!

**Comment by ClemensLode** [comment]
> @ClemensLode what did you do in the end to make the images the proper size in the generated document? In the example you shared the resulting images are very big. Thank you!

Well, I do not care about the size of the images as they are adapted by the ebook reader according to the page size. I guess it would be different if you wanted them half the size of the page etc.

If you take a look at the book template I am working on (https://www.overleaf.com/latex/templates/book-template-for-amazon-kdp-leanpub-and-google-play-e-book-and-pdf-2023/ymygsdrsyvsq), you also see that the images in the PDF are way too large. But if you download the EPUB and look at it in, for example, the Kindle Previewer, the images look fine.

In the template, I added a switch. If you compile it as XeLaTeX (and make a small change in the latexmkrc, commenting out the tex4ebook call), a proper PDF with proper formatting, image sizes, etc. is generated. If you use pdfLaTeX (and calling tex4ebook in latexmkrc), a PDF is generated that you can use as a preview (with image sizes way out of proportion), but also the EPUB file is created where everything is fine :)

**Comment by michal-h21** [comment]
@hendricius you can use various tricks to change image sizes: https://www.kodymirus.cz/tex4ht-doc/Howto.html#change-image-size-and-resolution

**Comment by hendricius** [comment]
@ClemensLode great template you are working on. Also thanks for the feedback!

@michal-h21  thanks a lot for the input too.
