### ISSUE TITLE
Epub Metadata: Tags?

### ISSUE THREAD

**Issue by hanetzer** [michal-h21/tex4ebook#104]
Is there a mechanism for this? Such that, in a book about first century Roman administration, I could include metadata tags such like Caesar, Procurators, and so on? When using the pdfx package I can add tags in the xmpdata block, like so:

```latex
\begin{filecontents*}[overwrite]{\jobname.xmpdata}
    \Author{Foo}
    \Title{First Century Roman Administration}
    \Keywords{Caesar\sep Procurator}
\end{filecontents}
```

and those Keywords are recognized by and listed by Calibre.

**Comment by michal-h21** [comment]
You can add metadata using `\Configure{OpfMetadata}{metadata}` to Epub. You can use Dublin Core elements, for example the `dc:subject`, as in this config file:

```
\Preamble{xhtml}
\Configure{OpfMetadata}{\HCode{<dc:subject id="sbj01">Number Theory</dc:subject>}}
\begin{document}
\EndPreamble
```

**Comment by hanetzer** [comment]
and for multiple tags, can I repeat the \Configure{OpfMetadata} block multiple times? or is there another construction I should use?

**Comment by michal-h21** [comment]
Yes, it can be used multiple times. The metadata is added each time it is used.
