### ISSUE TITLE
Problems with dc:creator

### ISSUE THREAD

**Issue by carlosnatalino** [michal-h21/tex4ebook#111]
Hi,

I am trying to set the <dc:creator> tag. It seems something similar to #82. I followed your advice in #25 and added the following to my `tex4ebook.cfg`:

```
\Configure{@author}{\let\footnote\@gobble}
```

However, this is what shows in the `content.opf`:
```
<dc:creator>gobbleAnonymous</dc:creator>
```

If I change the entry in `tex4ebook.cfg` to:

```
\Configure{@author}{Author}
```

However, this is what shows in the `content.opf`:
```
<dc:creator>AuthorAnonymous</dc:creator>
```

Versions:
- tex4ht.c (2018-07-03-10:36 kpathsea)
- tex4ebook v0.3j

Can you please help me understand/fix this issue?

**Comment by michal-h21** [comment]
`\Configure{@author}` is meant for local redefinition of problematic commands, such as footnote used in `\author`. If you don't use `\author` in your document, you can declare author in the configuration file like this:
```

\Preamble{xhtml}
\def\Author{Author}
\begin{document}
\EndPreamble
```
