### ISSUE TITLE
equation environment results in giant equations?

### ISSUE THREAD

**Issue by peeterjoot** [michal-h21/tex4ebook#113]
Is there a way to configure labelled equations to not be incredibly giant?  Example:

\begin{equation}\label{eqn:prerequisites:40}
\mathbf{x} = x \mathbf{e}_1 + y \mathbf{e}_2 + z \mathbf{e}_3,
\end{equation}

which seems to be forced into a square, and then ends up taking most of the page (see attached screenshot.)

<img width="493" alt="Screen Shot 2023-08-17 at 1 09 20 AM" src="https://github.com/michal-h21/tex4ebook/assets/163208/a1178328-76a5-44a1-8092-5c6a3655b4f8">

The inline equations have a reasonable size.

**Comment by michal-h21** [comment]
You can try this build file to set the image size: 

```lua
local domfilter = require "make4ht-domfilter"

local process = domfilter {
  function(dom)
    for _, image in ipairs(dom:query_selector(".equation img")) do
      local src = image:get_attribute("src")
      if src then
        local m = io.popen("identify -ping -format '%w' " .. src, "r")
        local result = m:read("*all")
        m:close()
        print(result)
        -- change this to your liking
        local factor = 0.6
        local newwidth = (tonumber(result) or 0) * factor
        if newwidth > 0 then
          local style = image:get_attribute(style) or ""
          style = style .. string.format("width:%spx;" , newwidth)
          image:set_attribute("style", style)
        end
      end

    end

    return dom
  end
}

Make:match("html$", process)

```

There is a factor variable, which you can change to get the correct size.

**Comment by peeterjoot** [comment]
Thanks for the suggestion.  I kept decreasing the factor size (down to 0.4), looking for it to have an effect, but was not seeing anything.  Then I discovered that this seems to work for the first image, but not for any of the rest.  Here is the first image of an equation (with factor = 0.4), previously huge

<img width="495" alt="Screen Shot 2023-08-17 at 8 14 00 AM" src="https://github.com/michal-h21/tex4ebook/assets/163208/000678d8-b5a2-43a0-bf1e-4972f9b408dc">

but the one that I was using as a benchmark in this case, is not changed at all:

<img width="495" alt="Screen Shot 2023-08-17 at 8 14 28 AM" src="https://github.com/michal-h21/tex4ebook/assets/163208/ba458c25-5203-43df-bb69-7dcddb1c04df">

In general, I am getting a random text size for each equation:

<img width="495" alt="Screen Shot 2023-08-17 at 8 18 00 AM" src="https://github.com/michal-h21/tex4ebook/assets/163208/5ef9d439-3d93-4831-9ef3-69e8e259f9d9">
<img width="495" alt="Screen Shot 2023-08-17 at 8 18 05 AM" src="https://github.com/michal-h21/tex4ebook/assets/163208/4b366fdb-b8d3-4e36-b3cb-225608f53e3a">
<img width="495" alt="Screen Shot 2023-08-17 at 8 18 14 AM" src="https://github.com/michal-h21/tex4ebook/assets/163208/729b49ec-df3a-4e91-809b-9e465b3c94fd">

Also related, is the fact that each equation ends up as a square image.  When the equation is a single line, this results in so much space around the equation, that it looks absolutely horrible.  Using Kindle previewer, that surrounding square box is evident if you click on the equation:

<img width="495" alt="Screen Shot 2023-08-17 at 8 18 18 AM" src="https://github.com/michal-h21/tex4ebook/assets/163208/7fa403fe-8c66-45c0-a431-7d83bcf3c0f6">

In the case of a large, multi-line equation, this whitespace padding at the top and the bottom of the equation is minimized.  Example:

<img width="495" alt="Screen Shot 2023-08-17 at 8 23 10 AM" src="https://github.com/michal-h21/tex4ebook/assets/163208/670f0878-26e1-452e-bcb7-c7fa0c9fa11c">

but it is really bad for single line equations (above.)

**Comment by peeterjoot** [comment]
New discovery.  It appears that the scaling issue is introduced when the epub format is imported into kindle previewer.  If I try with the calibre epub browser, the equation sizes and scaling all works very nicely:

<img width="480" alt="Screen Shot 2023-08-17 at 8 43 51 AM" src="https://github.com/michal-h21/tex4ebook/assets/163208/c19ae313-ee90-4e1e-98de-2e819d3e5679">

(in this particular epub viewer, the equation itself is barely visible, since it's black on black, but if you can see it, the size is actually great.)

**Comment by michal-h21** [comment]
You can also try this build file, which sets the width attribute, instead of inline CSS. Maybe it will work better with the Kindle previewer, but I doubt it.

```lua
local domfilter = require "make4ht-domfilter"

local process = domfilter {
  function(dom)
    for _, image in ipairs(dom:query_selector(".equation img")) do
      local src = image:get_attribute("src")
      if src then
        local m = io.popen("identify -ping -format '%w' " .. src, "r")
        local result = m:read("*all")
        m:close()
        print(result)
        -- change this to your liking
        local factor = 1 
        local newwidth = (tonumber(result) or 0) * factor
        if newwidth > 0 then
          -- local style = image:get_attribute(style) or ""
          -- style = style .. string.format("width:%spx;" , newwidth)

          image:set_attribute("width", tostring(math.floor(newwidth)))
        end
      end


    end

    return dom
  end
}

Make:match("html$", process)

```

**Comment by peeterjoot** [comment]
I tried 'tex4ebook -f mobi'. Kindle previewer inappropriately rescales the resulting formula pictures, as it did with the epub formatted book (unlike other epub viewers like calibre, which handle equations generated by the tex4ebook epub format properly).

Kindle itself fails to process the tex4ebook mobi format after upload "! Reflowable mobi input is not supported.
There was a problem processing your file. Please check your file and try again."

I don't think that this is an intrinsic problem with tex4ebook, but is an issue in the kindle stack.
