### ISSUE TITLE
Problem with Komascript/DeclareNewTOC 

### ISSUE THREAD

**Issue by cedounet** [michal-h21/tex4ebook#114]
The new Listofflocharts only show up in the pdf not in htlatex files..

`\documentclass{scrbook}
\DeclareNewTOC[
type=flowchart,%
types=flowcharts,% ,
float,
name=Flowchart,%
listname = {List of Flowcharts}
]{loc}
\setuptoc{loc}{chapteratlist}

\begin{document}
\begin{flowchart}[!htb]
\caption{A flowchart}
\end{flowchart}

\begin{figure}[!htb]
\caption{A figure}
\end{figure}
\listofflowcharts
\listoffigures

\end{document}`

If i do lualatex mwe.tex then cat mwe.loc I get:
\contentsline {flowchart}{\numberline {1}{\ignorespaces A flowchart}}{1}{}% \providecommand \tocbasic@end@toc@file {}\tocbasic@end@toc@file  
and the pdf is as expected

If I do  make4ht --lua -a debug mwe.tex then cat mwe.loc I get an empty file:
\providecommand \tocbasic@end@toc@file {}\tocbasic@end@toc@file  

PS: Issue popped up in 

Issue popped up in https://github.com/hendricius/the-sourdough-framework/pull/188  if you want context, but hopefully this MWE is enough.

Thanks 

C.

**Comment by michal-h21** [comment]
All table of contents like commands need a special treatment. All TOC entries are written to the `.4tc` file:


```latex
\expandafter\ifx\csname doTocEntry\endcsname\relax \expandafter\endinput\fi
\doTocEntry\tocloc{1}{\csname a:TocLink\endcsname{1}{x1-21}{}{\ignorespaces A flowchart}}{flowchart}\relax 
\doTocEntry\toclof{0.1}{\csname a:TocLink\endcsname{1}{x1-31}{}{\ignorespaces A figure}}{figure}\relax 
\doTocEntry\toclikechapter{}{\csname a:TocLink\endcsname{1}{x1-1000}{QQ2-1-3}{List of Flowcharts}}{9}\relax 
\doTocEntry\toclikechapter{}{\csname a:TocLink\endcsname{1}{x1-2000}{QQ2-1-4}{List of Figures}}{11}\relax 
```

As you can see  there are commands like `\tocloc` or `\toclikechapter`, each of them holds all necessary info to create links to the  destination. 

For each TOC type, such as `loc` in your case, you need to provide `\ConfigureToc{type}` command. This will provide formatting for the TOC entry. You can then print that entry type using `\TableOfContents[toc type]`. 

See [the documentation](https://www.kodymirus.cz/tex4ht-doc/Configurations.html#tables-of-contents) for more info and examples.

Try this configuration file, which redefines the ` \listofflowcharts` command to use TeX4ht's commands:


```latex

\Preamble{xhtml}
\renewcommand\listofflowcharts{%
\chapter*{\listoflocname}%
\TableOfContents[loc]%
}
\ConfigureToc{loc}{\HCode{<span class="lofToc">}}{\ }{}{\HCode{</span><br />}}

\begin{document}
\EndPreamble
```

The `\listoftocname` command is provided by Koma Script and keeps the "List of Flowcharts" string.

If it works, move your `\DeclareNewTOC` to a `.sty` file, and create corresponding `.4ht` file: https://www.kodymirus.cz/tex4ht-doc/ForDevelopers.html#tutorial-basic-support-for-a-new-package

**Comment by cedounet** [comment]
Thanks @michal-h21, let me try that.

**Comment by cedounet** [comment]
Sorry forgot to close it.  Works well.
