### ISSUE TITLE
Problem with TOC (possibly due to tocloft)

### ISSUE THREAD

**Issue by claell** [michal-h21/tex4ebook#119]
![grafik](https://github.com/michal-h21/tex4ebook/assets/6171135/69afe883-28f1-4155-8015-5d63acd7feb4)

See the screenshot (from Calibre viewer).

The chapter numbers are displayed twice.

I use tocloft to customize my TOC. Might this have something to do with it?

**Comment by claell** [comment]
After a lot of unnecessary testing to create a MWE, I finally learned that this is caused by the format specified for `tex4ebook`.

MWE:
```
\documentclass{book}
\begin{document}

\tableofcontents

\chapter{Test}

\end{document}
```

`tex4ebook -f epub3 test.tex` causes it. `tex4ebook test.tex` works fine.

Possibly, for EPUB3, the TOC is formatted as a numbered list (or at least displayed like that in Calibre Viewer)? But that are just random guesses. I also noticed, that the second number for EPUB3 is included in the hyperlink, whereas the number for EPUB is not included in the link.

**Comment by claell** [comment]
Ah, alright. Mh, I copied the development version of `tex4ebook` into the TeX Live folder. But possibly it relies on other libraries or something else is happening so the issue occurs.

Thanks for providing a fix!

**Comment by claell** [comment]
For me, this seems still not working in the development version of `tex4ebook`.

**Comment by claell** [comment]
The provided configuration file didn't work for me, either.

Run with `tex4ebook -c tex4ebook.cfg -f epub3 test.tex`.

**Comment by claell** [comment]
Found my problem. I didn't manually update the contents of `C:\texlive\2023\texmf-dist\tex\latex\tex4ebook`, before. After doing that, it now works properly!

**Comment by claell** [comment]
Note, that it produces slightly different results for me (compared to EPUB):

EPUB:
![grafik](https://github.com/michal-h21/tex4ebook/assets/6171135/db74ce08-2e43-46de-9b6a-2f536b5db501)

EPUB3:
![grafik](https://github.com/michal-h21/tex4ebook/assets/6171135/e41393aa-3d76-4357-9e81-e70d01e999dd)

This might not be problematic (at least to me, it is just a cosmetic difference), but I wanted to document it.

**Comment by michal-h21** [comment]
The difference in TOC between Epub and Epub 3 is because Epub 3 requires specific format of the HTML code used for TOC - it is used as TOC in Epub readers. So this is the reason for the difference.
