### ISSUE TITLE
Running master version of tex4ebook causes an error

### ISSUE THREAD

**Issue by claell** [michal-h21/tex4ebook#123]
```
tex4ebook test.tex
[STATUS]  tex4ebook: Conversion started
[STATUS]  tex4ebook: Input file: test.tex
c:\texlive\2023\texmf-dist\scripts\tex4ebook\tex4ebook:130: attempt to call a nil value (field 'make_path')
C:\texlive\2023\bin\windows\runscript.tlu:921: command failed with exit code 1:
texlua c:\texlive\2023\texmf-dist\scripts\tex4ebook\tex4ebook test.tex
```

This happened after I replaced the files in `C:\texlive\2023\texmf-dist\scripts\tex4ebook` with the current master branch from GitHub.

**Comment by michal-h21** [comment]
The `make_path` was introduced in recent versions of `make4ht`. I should update both `make4ht` and `tex4ebook` soon, because it seems that manual updating is causing lot of problems.

**Comment by vojtech-cerveny** [comment]
Hey, same here on macos - 

```
excessus/public/files on  master [$!] on 🐳 v25.0.3 (orbstack) took 2s 
➜ which tex4ebook 
/usr/local/bin/tex4ebook

excessus/public/files on  master [$!] on 🐳 v25.0.3 (orbstack) 
➜ tex4ebook test.tex
[STATUS]  tex4ebook: Conversion started
[STATUS]  tex4ebook: Input file: test.tex
/usr/local/bin/tex4ebook:130: attempt to call a nil value (field 'make_path')
```

**Comment by michal-h21** [comment]
I've just updated both `make4ht` and `tex4ebook` on CTAN last Friday. The update seems to be already available in TeX Live. Try to update the distribution, and remove the manually installed `tex4ebook` and `make4ht` directories from your local TEXMF tree, to prevent possile clashes.

**Comment by claell** [comment]
Should be fixed. I also recently completely upgraded to TeX Live 2024. Thanks for your quick support!
