### ISSUE TITLE
Ways to integrate custom `.4ht` files

### ISSUE THREAD

**Issue by claell** [michal-h21/tex4ebook#128]
Sometimes, custom `.4ht` files are required to support some packages.

Currently, I know that these files can be placed in the main project directory where `tex4ebook` is executed.

However, I am not sure, whether they can also be included from different locations (and how). Is that possible via a config file?

And probably, one could also copy them to some global folder somewhere?

**Comment by michal-h21** [comment]
If you have packages shared by multiple projects, placing them in your `$TEXMFHOME` tree is best. See this [blog post](https://www.ugr.es/~ftorralbo/blog/programming/local-texmf/). For example, on Linux, you could place  them in a subdirectory of `~/texmf/tex/latex`, for example:

      ~/texmf/tex/latex/mypackages/

You can put both `.sty` and `.4ht` files here. You can include them without specifying the full path, LaTeX will find them just by the name.

**Comment by claell** [comment]
Perfect, thanks!
