### ISSUE TITLE
"attempt to index a nil value" error with miktex

### ISSUE THREAD

**Issue by u-fischer** [michal-h21/tex4ebook#17]
Due to a tex.sx question I made some small tests with miktex. I made this call on an hello-world document:

```
  G:\Z-Test>texlua E:\TeX\ebook-texmf\tex\latex\tex4ebook\tex4ebook.lua test-utf8
```

 and get this error:

E:/TeX/ebook-texmf/tex/latex/tex4ebook/list-fonts.lua:49: attempt to index local
 'sanitized' (a nil value)

The error is from this line:

```
   local sanitized = record.sanitized or record.names
```

and an inspection of the record table shows that is contains neither a sanitzed nor a names field. 

The error doesn't appear in texlive as in texlive the luatex name cache is not found at all and so most code in list-fonts.lua finds only empty tables: tex4ebook looks only for lua-files, while texlive by defaults creates only a lua.gz and a luc-file. Unpacking luaotfload-names.lua.gz to luaotfload-names.lua triggers the error also in texlive2014.

Ulrike Fischer

**Comment by michal-h21** [comment]
Hi Ulrike,
thank you for spotting this. I removed font including option, as it never worked. Could you please test whether it works now?

**Comment by u-fischer** [comment]
The error is gone. Both system complain that tidy couldn't be found, so I will have to put it in the path. Miktex additionally complains that zip.exe couldn't be found (miktex often gives such applications new names to avoid clashes  and so has a miktex-zip.exe instead of zip.exe as in texlive.)

**Comment by michal-h21** [comment]
Yes, tidy must be installed separately. Do you think it would be better to
call `miktex-zip` in case normal `zip` command fails, or to include `zip`
utility as dependence? I would prefer latter.

2015-01-31 18:18 GMT+01:00 u-fischer <notifications@github.com>:

**Comment by u-fischer** [comment]
Well it shouldn't be very difficult for miktex user to make a copy from miktex-zip.exe and name it zip.exe.
On the other side it is an additional step. So most users would probably prefer that the scripts tries "zip.exe" and then "miktex-zip.exe" ;-)

**Comment by michal-h21** [comment]
Yeah, I added test for `zip` command, `miktex-zip` is used otherwise.

2015-01-31 19:20 GMT+01:00 u-fischer <notifications@github.com>:

**Comment by michal-h21** [comment]
Ulrike, do you get the same error as the OP with make4ht?:

---------
Thanks for the answer: I can't quite tell if my implementation of your
solution was unsuccessful or if I have missed an important underlying
requirement. I get an error message as described: [string
"Make:htlatex{}..."]:1: attempt to index global 'Make' (a nil value)
.../texmf/scripts/lua/make4ht/mkutils.lua:281: assertion failed! –  EngBIRD
<http://tex.stackexchange.com/users/69378/engbird> 9 hours ago
<http://tex.stackexchange.com/questions/225783/install-make4ht-with-miktex/225800?noredirect=1#comment531251_225800>
--------
http://tex.stackexchange.com/a/225800/2891


2015-01-31 19:46 GMT+01:00 Michal Hoftich <michal.h21@gmail.com>:

**Comment by u-fischer** [comment]
Michal, I have no idea how the OP did call make4ht and so can't test. (I don't know enough about tex4ht/make4ht to be able to guess what the OP did).

**Comment by u-fischer** [comment]
Regarding the zip.exe: epub2.env contains calls to zip too. Does it need some miktex adaption??

**Comment by michal-h21** [comment]
I think epub2.env isn't used anymore, it was fully replaced by make4ht. I
should remove it.

2015-02-04 18:55 GMT+01:00 u-fischer <notifications@github.com>:
