### ISSUE TITLE
mathcal letters not recognized

### ISSUE THREAD

**Issue by shasn** [michal-h21/tex4ebook#18]
Hi Michal,

I tried to compile a file with lots of math equations and realized that long equations tend to get compiled to .png first and then embed into the epub file. In some cases if I tried to compile something short like `$\mathcal{O}$`, the compiler would simply go to a letter `𝒪` (instead of a png first), which appears properly in html files but does not in the ebook. I think that is because kindle does not support calligraphic letters. Is there a way to let them go to images first?

Regards,
Han

**Comment by michal-h21** [comment]
Hi Han,

you can request conversion of inline math to pictures with `pic-m` option
(to be used as `tex4ebook -f mobi filename "xhtml,pic-m" or in the .cfg
file in the `\Preamble command). Similar options for various math
environments exists, see

http://www.cvr.cc/?p=504

you may also be interested in this answer:

http://tex.stackexchange.com/a/235472/2891

I am not sure that svg works in all Kindle versions, but it is clearly
superior to bitmap images.

Regards,
Michal

**Comment by shasn** [comment]
Hi Michal,

Thank you for the information. I tried the solution you provided with my windows laptop and texlive. The command `"tex4ebook filename "xhtml, pic-m"` converts inline equations to images. I basically did epub first and then converted it to mobi with kindlegen and it shows good result. 

As you mentioned svg would do better jobs than png does. I also tried the scripts in the link. The shape does look good; however with options `-f epub -c myconfig.cfg -e a.mk4` the compiler would give random svg images with error messages like 

`ERROR: FontEngine: error reading file c:\texlive\2014\texmf-dist\fonts\type1\public\amsfonts\cm\cmmi8.pfb`

I am still not sure where the problem comes from, but at least with png options I could read the math book with my kindle. I appreciate the help you provided.

Regards,
Han

**Comment by michal-h21** [comment]
Hi Han,

I am happy that it works now. The problem with svg conversion should be
fixed in current dvisvgm version, which isn't in TeX Live yet. See [1] for
some details.


Regards,
Michal

[1] https://answers.launchpad.net/dvisvgm/+question/262501
