### ISSUE TITLE
Some special umlauts appear as images

### ISSUE THREAD

**Issue by horvathp** [michal-h21/tex4ebook#21]
Hi,
I'm trying to create ebooks that contain some exotic umlauts, such as the \H{o} (ő) and \H{u} (ű) and their capitalized versions. 
I use inputenc with the utf8 option.
Every instance of these letters appear as an image in the final version if run through tex4ebook which looks somewhat weird and takes up a lot of space. If run through --lua, they don't appear at all. Is there a clever way of including these problematic letters "natively" into the document?

Best regards,
P.

**Comment by michal-h21** [comment]
Hi Peter,

try to use "new-accents" tex4htoption. Ie:

    tex4ebook filename "new-accents".


Note that you need to use also fontenc package wth T1 option.

Best regards,
Michal

**Comment by horvathp** [comment]
Great, thank you very much, it works (with luainputenc). 
Best regards,
Peter
