### ISSUE TITLE
Minor readability problem with "mame lua"

### ISSUE THREAD

**Issue by JalapenoGremlin** [michal-h21/tex4ebook#24]
When I ran tex4ebook I was very confused by the log line:
    "mame lua"

At first I thought it was a misspelling of "maim":
> verb (used with object)
> 1. to deprive of the use of some part of the body by wounding or the like; cripple:
> The explosion maimed him for life.
> 2. to impair; make essentially defective:
> The essay was maimed by deletion of important paragraphs.

I had to read the code:
```
if args.lua then
  print("Mame lua")
  latex_cmd="dvilualatex"
end
```
I then had to  and investigate a bit about the author , who I  I think,  is in the Czech Republic. Then use Google translate to find out that  "mame" is Czech (and Slovak) for "We have."

I have no objections to using natural languages other than English, but the rest of the code uses English.  

I have never programmed Lua, so I do know know if Lua supports something similar to python's `gettext` and creating .po files for message translation.
```python
from gettext import gettext as _

# Deepest apologies if this is incorrect. I just type 'This is a comment'
# into Google translate
print _("Toto je komentář")
```

---
So the long bug report for the simple question  :stuck_out_tongue_winking_eye:

Am I correct in that the the print statement is stating the following?

> The command tex4ebook has been called with the -lua argument

or

>  Lua specified, using dvilualatex.

**Comment by michal-h21** [comment]
Thanks for the report, you are right this is Czech message stating "We have Lua", so nothing really useful. It is just some debugging message which isn't really useful anymore, so I've removed it.

**Comment by JalapenoGremlin** [comment]
Cool. 
Sorry about such a long bug report for such a trivial matter. I just wanted to make certain I understood correctly. (As a programmer I, too, often have remaining debug messages, so I completely understand). 

The good news is that I've started looking into lua :smile:

**Comment by michal-h21** [comment]
That's fine, I usually use English for comments, but sometimes I use Czech when I hunt some frustrating and stupid bug. Thankfully, I usually don't forget to remove it later, not in this case :).
