### ISSUE TITLE
glossary anchors are not valid XHTML

### ISSUE THREAD

**Issue by 414n** [michal-h21/tex4ebook#26]
Greetings,

dunno if it's a bug of tex4ebook or in htlatex in general, but when using the `glossaries` package to generate a glossary, the anchors created are in the form 
```xml
<a href="glossarypage.html#glo:term">
```
That colon between **glo** and **term** breaks epub validation and those anchors do not work on an epub reader.
The workaround I currently use is this:
 - further process the epub produced by tex4ebook with calibre (would've done it anyway)
 - add a "search and replace" option on calibre command line to translate those colons to underscore chars: `--sr1-search 'glo:(\w)' --sr1-replace 'glo_\1'`

Should this be managed by tex4ebook?

**Comment by michal-h21** [comment]
I think this issue will be present in tex4ht as well, glossaries automatically add `glo:` prefix to the links. `tex4ebook` supports Lua filters, which can be used to fix such stuff: Save this as `sample.mk4`:

```
local filter = require "make4ht-filter"

local function fix_href_colons(s)
  return s:gsub('(href=".-")', function(a)
    if a:match("[a-z]%://") then return a end
    return a:gsub(":","_")
  end)
end

local function fix_id_colons(s)
  return s:gsub('(id=".-")', function(a)
    return a:gsub(":", "_")
  end)
end

local process = filter {fix_href_colons, fix_id_colons}
Make:match("html$", process)

```

you can compile it using `tex4ebook -e sample.mk4 filename`

**Comment by michal-h21** [comment]
I've added this filter to `make4ht`, so you can use just following build file:
```

local filter = require "make4ht-filter"

local process = filter {"fix-links"}

Make:match("html$", process)

```

**Comment by 414n** [comment]
Wow, faster than "fast" :wink: 
Thank you very much, will test it soon!

**Comment by michal-h21** [comment]
I was so fast that I forgot to push my changes to Github. It should be fine now: https://github.com/michal-h21/make4ht

**Comment by 414n** [comment]
Thanks @michal-h21, works like a charm!
Closing the issue
