### ISSUE TITLE
attempt to call field 'process_args' (a nil value)

### ISSUE THREAD

**Issue by DavidGriffith** [michal-h21/tex4ebook#29]
I'm getting this error when trying to process a simple .tex hello-world document:

```
$ tex4ebook hello-world.tex 
/usr/local/bin/tex4ebook:126: attempt to call field 'process_args' (a nil value)
$
```

**Comment by michal-h21** [comment]
It seems that you might have some really old version of [make4ht](https://github.com/michal-h21/make4ht). The version shipped with TeX Live should work without problem.

**Comment by DavidGriffith** [comment]
I'm on Debian Jessie, which installs TeX Live 2014.  There is nothing higher in the backports repo.  I was using the latest version of make4ht from https://github.com/michal-h21/make4ht

**Comment by michal-h21** [comment]
This is strange, it seems like if `tex4ebook` used `make4ht` from TL instead of your local version. Could you try to run the following Lua code using `texlua` command?

```
kpse.set_program_name "luatex"
local test = require "mkparams"
print(test.process_args)
```

**Comment by DavidGriffith** [comment]
```nil```

**Comment by michal-h21** [comment]
So it seems that an old version of `mkparams.lua` included in TL 2014 is used. It seems that main TL tree is used instead of TEXMFHOME. Could you try to install `make4ht` again, but to `TEXMFLOCAL`? I think this should do the trick:

     make install TEXMFHOME=`kpsewhich -var-value=TEXMFLOCAL`

**Comment by DavidGriffith** [comment]
I was already using such a modification when I asked about installing to TEXMFLOCAL instead of TEXMFHOME in #28.  Deleted and reinstalled make4ht as requested.  No change in behavior.

**Comment by michal-h21** [comment]
This is really strange, it seems that you must have another version of `make4ht` installed somewhere, you would get `module 'mkparams' not found:` error if `tex4ebook` couldn't load it at all. Does 

    kpsewhich mkparams.lua 

report the correct location?

**Comment by DavidGriffith** [comment]
```/home/dave/texmf/tex/latex/make4ht/mkparams.lua```

I deleted that and ran ```texhash```.  Then I discovered I needed to install tex4ht.  I can now build an epub, but now I'm having problems with formatting.  I'll open a new ticket for that.
