### ISSUE TITLE
LaTeX formatting gone when building to epub

### ISSUE THREAD

**Issue by DavidGriffith** [michal-h21/tex4ebook#30]
I'm pretty sure I'm doing something wrong.  When I compile to epub, most of the LaTeX formatting is gone.  In particular -- newlines, paragraph breaks, and centering are most notably absent.  What am I missing?

**Comment by michal-h21** [comment]
The formatting should be preserved, paragraphs and line breaks certainly. This can be an issue with `tex4ht` installation. What do you get when you compile your file with `htlatex`?

**Comment by DavidGriffith** [comment]
Using ```htlatex``` I get centering, paragraphs, and line breaks are rendered correctly.  No pagebreaks appear in the html, but that's to be expected for the format.  In the generated ```.dvi```, I see aforementioned things in the right places but ```\ldots``` commands get turned into ```x```.

**Comment by michal-h21** [comment]
Could you please post your source files and the epub somewhere? This looks that something is still broken, because you should get basically the same formatting with `htlatex` and `tex4ebook`.

**Comment by DavidGriffith** [comment]
https://drive.google.com/open?id=0BwWxJGzBXGUjYWJydHZsRWlvaEk

**Comment by michal-h21** [comment]
I am sorry, but I can't find any TeX documents in the link above, only PDF and Docx documents.

**Comment by DavidGriffith** [comment]
Please try the updated link

**Comment by michal-h21** [comment]
You need an configuration for page breaks on `\newpage`, like one provided in [this answer](http://tex.stackexchange.com/a/346889/2891) on TeX.sx.

**Comment by DavidGriffith** [comment]
Thanks!
