### ISSUE TITLE
Strange code appears in readme.md

### ISSUE THREAD

**Issue by senthilmm** [michal-h21/tex4ebook#31]
tex4ebook uses tex4ht^[\url{http://www.tug.org/tex4ht/}] for conversion from LaTeX to html.

**Comment by michal-h21** [comment]
Yes, direct LaTeX code is sometimes used. In this case, I've found that Pandoc has `autolink_bare_uris` extension, which detect URLs and place them in links. So `\url` commands are no longer necessary and I've removed them.

**Comment by senthilmm** [comment]
Thanks. Do you need the caret symbol '^', in front of the already enclosed URLs with '[' and ']'.

**Comment by michal-h21** [comment]
These are converted to footnotes in the PDF version of the manual (Pandoc's `inline_notes` extension)
