### ISSUE TITLE
Illegal parameter number in definition of \@thanks.

### ISSUE THREAD

**Issue by richelbilderbeek** [michal-h21/tex4ebook#37]
I am working on [a Travis CI file](https://github.com/richelbilderbeek/tex4ebook/blob/master/.travis.yml) for this repo. 

When I do

```
tex4ebook tex4ebook-doc.tex
```

 I get the error (as can be found in [the current log](https://travis-ci.org/richelbilderbeek/tex4ebook/jobs/322871689#L2307) as well)

```
! Illegal parameter number in definition of \@thanks.
<to be read again> 
                   1
l.20 \maketitle
               
? 
```

The Travis CI script (copied from [.travis.yml](https://github.com/richelbilderbeek/tex4ebook/blob/master/.travis.yml)) does as follows, in the root folder of this repo:

```
install:
  - sudo apt-get install -qq luatex texlive-base texlive-luatex pandoc latexmk texlive texlive-xetex tex4ht texlive-latex-extra 
  # make4ht
  - git clone https://github.com/michal-h21/make4ht
  - cd make4ht
  - make
  - sudo make install
  - cd ..

script:
  - make
  - sudo make install
  - tex4ebook tex4ebook-doc.tex
```

How to fix this?

**Comment by michal-h21** [comment]
Git tags are used fro version info and the release date. Does `git fetch --tags` help?

**Comment by richelbilderbeek** [comment]
I assume you suggest to use the `devel` branch first, will try now.

**Comment by michal-h21** [comment]
No, it should work in `master`. Without updated release tags you may get wrong content for `\gitdate` and `\gitversion` macros.

**Comment by richelbilderbeek** [comment]
Tried, but this does not make any difference:

```

install:
  - sudo apt-get install -qq luatex texlive-base texlive-luatex pandoc latexmk texlive texlive-xetex tex4ht texlive-latex-extra 
  # make4ht
  - git clone https://github.com/michal-h21/make4ht
  - cd make4ht
  - make
  - sudo make install
  - cd ..

script:
  # From https://github.com/michal-h21/tex4ebook/issues/37#issuecomment-354447097
  - git fetch --tags
  # Install globally
  - make
  - sudo make install
  # Run
  - tex4ebook tex4ebook-doc.tex
```

**Comment by michal-h21** [comment]
Ah, this issue was something different than I expected.  d7f557d405d12c9a5aabc3a6bd546137602db054  should fix it. I also added the `.travis.yml` file you posted and it seems to pass. Thanks!

**Comment by richelbilderbeek** [comment]
Great, always happy to improve the quality of software. Keep up the good work!
