### ISSUE TITLE
How to change output directory?

### ISSUE THREAD

**Issue by bblanchon** [michal-h21/tex4ebook#42]
Hi,

Is there a command line option to change the output directory?

For example, `latexmk` takes a jobname like that:

    latexmk -jobname=output/fancy_name main

Please apologize if this is a dumb question, but I've been looking for the answer for quite a long time.

Regards,
Benoit

**Comment by michal-h21** [comment]
Hi Benoit,

I've just added the `--output-dir` or `-d` option to `tex4ebook`. It is already supported by `make4ht`, so I guess that I just forgot to include it in `tex4ebook` as well.

Best regards,
Michal

**Comment by bblanchon** [comment]
Hi Michal,

That is awesome, thank you very much!
And thank you for this very cool project.

Regards,
Benoit
