### ISSUE TITLE
Hiding inline TOC

### ISSUE THREAD

**Issue by arkonbob** [michal-h21/tex4ebook#43]
Hi, 

Is it possible to hide the inline table of contents in the ebooks produced? By this I mean the pages in the book showing the table of contents. In an ebook this seems unnecessary because an embedded TOC is present (for example on either Kindle or iBooks, the user clicks the contents icon to show the embedded TOC as an overlay). Also in my case the embedded TOC is superior to the inline version, the latter is missing links to some sections of the book.

**Comment by arkonbob** [comment]
Thanks, that's actually answered another question I had re. how to add some content only in the ebook version and vice versa :-)

However for the TOC, that solution removes both the embedded and inline TOCs from the ebook version. So it looks like there is no way to hide the inline TOC while keeping the embedded TOC - is that what you meant?

**Comment by michal-h21** [comment]
It kept the embedded TOC displayed in the ebook reader for me. Can you show me a sample file with packages you use? It may be a bug.

**Comment by arkonbob** [comment]
I think I was too impatient - it looks like multiple compiles were necessary for the fix to take effect. Many thanks for the help.

**Comment by michal-h21** [comment]
Ah, this can happen, temporary files can sometimes cause problems. In this case it may help to delete *.aux, *.xref, *.4tc and *.4ct files and make clean compilation. `tex4ebook` executes LaTeX three times by default, it should be sufficient in most cases, but it may be necessary to make few more compilations in rare cases.
