### ISSUE TITLE
Wrong guillemets with csquotes

### ISSUE THREAD

**Issue by simifilm** [michal-h21/tex4ebook#44]
When using the `csquotes` package, `tex4ebook` produces incorrect guillemets. Consider the following MWE:

> \documentclass{article}
> \usepackage[ngerman]{babel}
> \usepackage[german=guillemets,autostyle=true]{csquotes}
> \begin{document}
> \enquote{Test} \enquote*{Test}
> \end{document}

The resulting document does not use guillemets but the much-greater-than (Unicode #8811 and #8810) and the greater-than signs (Unicode #60 and #62). While these look similar with certain fonts, they are *not* guillemets.

**Comment by simifilm** [comment]
Sorry, I should have explicitly said that this with LuaTeX. This is the `tex4ebook` call I'm using: `tex4ebook -f epub3 -l test.tex`.

**Comment by michal-h21** [comment]
Ah, I see. Try to save the following snippet as `tuenc-luatex.def` in your document's folder:

```
% tuenc-luatex.4ht, generated from tex4ht-4ht.tex
% Copyright 2017 TeX Users Group
%
% This work may be distributed and/or modified under the
% conditions of the LaTeX Project Public License, either
% version 1.3c of this license or (at your option) any
% later version. The latest version of this license is in
%   http://www.latex-project.org/lppl.txt
% and version 1.3c or later is part of all distributions
% of LaTeX version 2005/12/01 or later.
%
% This work has the LPPL maintenance status "maintained".
%
% This Current Maintainer of this work
% is the TeX4ht Project <tex4ht@tug.org>.
%
% If you modify this program, changing the
% version identification would be appreciated.
\immediate\write-1{version 2017-01-24-15:21}

\RequirePackage{luatexbase}
\RequirePackage{luacode}

\def\UnicodeEncodingName{OT1}
\input tuenc.def
\begin{luacode*}
  local fontspec = require "fontspec-4ht"
  luatexbase.add_to_callback("pre_linebreak_filter", fontspec.char_to_entity, "Char to entity")
  luatexbase.add_to_callback("hpack_filter", fontspec.char_to_entity, "hpack-char-to-entity")
  luatexbase.add_to_callback("vpack_filter", fontspec.char_to_entity, "hpack-char-to-entity")
\end{luacode*}
\Hinput{tuenc-luatex}
\endinput
```

I will update it in `tex4ht` if it doesn't make any issues

**Comment by simifilm** [comment]
Thanks, but this doesn't seem to work. AFAICS `tuenc-luatex.def` isn't even loaded although it's in the same folder as the document file. According to the log, only `ot1enc.def` is loaded.

**Comment by michal-h21** [comment]
@simifilm oh, my bad, it shouldn't be `tuenc-luatex.def` but `tuenc-luatex.4ht`.

**Comment by simifilm** [comment]
That did the trick. Thanks a lot.

**Comment by michal-h21** [comment]
OK, I've updated tex4ht sources with fix for LuaLaTeX and XeLaTeX, it should be included in TL soon.

**Comment by simifilm** [comment]
Great. Now off to bug #45 ;).
