### ISSUE TITLE
biblatex: \emph{} is ignored for titles

### ISSUE THREAD

**Issue by simifilm** [michal-h21/tex4ebook#45]
Consider the followng MWE:

> \documentclass[]{article}
> \usepackage{etoolbox}
> \usepackage[style=authoryear]{biblatex}
> \begin{filecontents*}{test.bib}
> @book{Spiegel.S:2007b,
> 	Address = {Marburg},
> 	Author = {Spiegel, Simon},
> 	Number = {16},
> 	Publisher = {Schüren},
> 	Series = {Zürcher Filmstudien},
> 	Standort = {Privat},
> 	Subtitle = {Zu einer Poetik des Science-Fiction-Films},
> 	Title = {Die Konstitution des Wunderbaren},
> 	Year = {2007}}
> \end{filecontents*}
> \addbibresource{test.bib}
> \begin{document}
> 
> Test\footnote{AA} 
> 
> \citetitle{Spiegel.S:2007b}
> \end{document}

I don't know what's going on here, but in this setup, the title of the cited book isn't printed in italics. If I leave the footnote out or put the `\citetitle` on the same line, it works.

**Comment by simifilm** [comment]
This is with `LuaTeX`by the way. This is the `tex4ebook` call I'm using: `tex4ebook -f epub3 -l test.tex`.

**Comment by michal-h21** [comment]
this was caused by spurious `\NoFonts` command in the footnote configuration. all formating which followed a footnote use have been lost. try the recent `tex4ebook` update

**Comment by simifilm** [comment]
Should this update already be on TL? I am on the latest versions here.

**Comment by michal-h21** [comment]
No, it is only on Github, I need to make some other fixes before I post the update to CTAN.
