### ISSUE TITLE
"sudo make install" barfs on "git fetch --tags" being run as root.

### ISSUE THREAD

**Issue by DavidGriffith** [michal-h21/tex4ebook#46]
```
$ sudo make install
[sudo] password for dave: 
git fetch --tags
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Makefile:25: recipe for target 'tags' failed
make: *** [tags] Error 128
```

Looking closer, it's this command that caused trouble: ```git fetch --tags```.   Adding ```-verbose``` doesn't show me anything useful.  On top of this, it seems that the Makefile doesn't agree with INSTALL.md anymore -- Makefile wants to install only to $(HOME)/texmf or /root/texmf.

**Comment by michal-h21** [comment]
Yes, the information in INSTALL.md was outdated, `make install` should be used without `sudo` as it install files to wrong locations. I've updated the instructions and the build file, the destination of the executable can be now selected in the user directory.

**Comment by DavidGriffith** [comment]
I think your commits on Oct 18 concluding with  640e76280d3a7c511fce163c0a9fff1b4c7327e4 fix the problems.

**Comment by michal-h21** [comment]
Thanks  for confirmation, so I think we can close this for now.
