### ISSUE TITLE
Division by zero error when options used with \includegraphics and using XeLaTeX

### ISSUE THREAD

**Issue by DavidGriffith** [michal-h21/tex4ebook#47]
Trying to build a memoir document using XeLaTeX...
If I use ```\includegraphics{foo}``` alone, the epub builds fine.  If I use ```\includegraphics[width=5em]{foo}``` alone, the epub builds fine.  But if I do both, I get a divide-by-zero error.  Just putting square brackets with nothing in them gives no indication of a problem except it fails with ```Test code:Make4ht: Fatal error. Command tex4ht returned exit code 256```.

Test tex
```
\documentclass{memoir}
\usepackage{graphicx}

\title{test document for tex4ebook}
\author{Joe Bloggs}

\begin{document}
\maketitle
\tableofcontents

\includegraphics{art/larry}

\includegraphics[width=5em]{art/larry}

\chapter{hello}
Hello World

\chapter{world}
 Whirled Peas

\end{document}
```
Build and failure:
```
tex4ebook -x test.tex
...
(/usr/share/texlive/texmf-dist/tex/generic/tex4ht/html4.4ht)
(/usr/share/texlive/texmf-dist/tex/generic/tex4ht/html4-math.4ht))
No file test.aux.
[1] [2]
No file test.4tc
l.11 --- TeX4ht warning --- Can not include graphics of type: bmp ---

! Package graphics Error: Division by 0.

See the graphics package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.13 \includegraphics[width=5em]{art/larry}
                                           
?
```

**Comment by DavidGriffith** [comment]
Where would the custom config files appear?  I'm not knowingly using any.  

That complaint about ```bmp``` confused me too.  The ```art/larry``` image is a .png file.  I'm not using any sort of BMP file in the project that prompted this issue filing.

**Comment by michal-h21** [comment]
The config file can be requested using the `-c` option, so you don't use any. Does the error show even if you use the file extension, `larry.png`? Could you post the image somewhere?

**Comment by DavidGriffith** [comment]
Extension doesn't affect anything.  There appears to be nothing special about the png.  I generated it by doing ```convert larry.tif larry.png```.  I tried other images, four in all, and using all of these provokes the same error.  Here's one of the ones I tried:

![foo](https://user-images.githubusercontent.com/1289035/47351596-26785600-d66d-11e8-8483-c0e1f8181f02.png)

**Comment by michal-h21** [comment]
This seems like some issue with `tex4ht` installation. Which TeX distribution do you use? It is best to use TeX Live 2018, as it always include the updated `tex4ht`. The provided image works for me with XeTeX as used engine, for LuaTeX and PdfTeX I had to provide a configuration file with list of extensions for images:

```
\Preamble{xhtml}
\DeclareGraphicsExtensions{.png,.svg,.jpg}
\begin{document}
\EndPreamble

```

**Comment by DavidGriffith** [comment]
I'm using TeX Live 2016 as installed through the Debian 9 repos.  I'll upgrade to testing and report back.

You suggestion gave me a very curious error and failure that looked like this:
```
(/usr/share/texlive/texmf-dist/tex/generic/tex4ht/html4-math.4ht))

! LaTeX Error: Missing \begin{document} in `'.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.13 \begin{document}
```

**Comment by michal-h21** [comment]
Ah, this is really old version, the image handling has been changed since then. It is best to use TL 2018, if possible.

**Comment by DavidGriffith** [comment]
I've upgraded to Debian Buster and TL 2018.  The problem is gone, but I found another one for which I'll start a new ticket.
