### ISSUE TITLE
Can't use svg package with xelatex

### ISSUE THREAD

**Issue by DavidGriffith** [michal-h21/tex4ebook#50]
```tex4ebook``` can't find the converted graphic file if the ```-x``` flag is used.  If ```-l``` is used or regular ```htlatex``` is used, then things work as expected.

Here's the test file:
```
\documentclass{article}
\usepackage{graphicx}
\usepackage{svg}
\parindent=0pt
\begin{document}
Hello world!\\
\includesvg{glider}\\
Wasn't that fun?
\end{document}
```

Here's a test SVG:
```
<?xml version="1.0" standalone="no"?><svg xmlns="http://www.w3.org/2000/svg" version="1.0" width="140" height="140"><g transform="matrix(20,0,0,20,10,10)"><path d="m0 0h6v6h-6zm0 2h6m-6 2h6m-4-4v6m2-6v6" style="fill:none;stroke:#000;stroke-width:.1;"/><circle cx="3" cy="1" r=".8"/><circle cx="5" cy="3" r=".8"/><circle cx="1" cy="5" r=".8"/><circle cx="3" cy="5" r=".8"/><circle cx="5" cy="5" r=".8"/></g></svg>
```

Invocation: 
```
tex4ebook -x -s test.tex 
...
(/usr/share/texlive/texmf-dist/tex/generic/tex4ht/color.4ht)
(/usr/share/texlive/texmf-dist/tex/generic/tex4ht/html4.4ht)
(/usr/share/texlive/texmf-dist/tex/generic/tex4ht/html4-math.4ht))
No file test.aux.
(./svg-inkscape/glider_svg-tex.pdf_tex
! Unable to load picture or PDF file './svg-inkscape/glider_svg-tex.pdf'.
<to be read again> 
                   }
l.56 ...h=\unitlength,page=1]{glider_svg-tex.pdf}}
                                                  %
?
```

**Comment by michal-h21** [comment]
It seems that the issue is caused by the `XeTeX` driver for `graphicx` and `xcolor` packages. It vanishes when `dvips` driver is requested instead. It can be requested in this way, for example:

```
\documentclass[
\ifdefined\HCode dvips\fi
]{article}
\usepackage{graphicx}
\usepackage{svg}
\parindent=0pt
\begin{document}
Hello world!\\
\includesvg{glider}\\
Wasn't that fun?
\end{document}
```

I haven't found a way to request it from `tex4ht`, without need to modify the TeX file.

**Comment by DavidGriffith** [comment]
Is this an upstream bug?

**Comment by michal-h21** [comment]
Probably  yes. We will need to fix it in `tex4ht` sources.

**Comment by DavidGriffith** [comment]
This fix doesn't appear to work:

```
Copy: cp "test.html" "test-epub/OEBPS"
Copy: cp "test.css" "test-epub/OEBPS"
Mimetype for tmp is not registered
Copy: cp "test.ncx" "test-epub/OEBPS"
Mimetype for opf is not registered
Mimetype for opf is not registered
Copy: cp "./svg-inkscape/glider_svg-tex-1.png" "test-epub/OEBPS/./svg-inkscape"
cp: cannot stat './svg-inkscape/glider_svg-tex-1.png': No such file or directory
Copy: cp "content.opf" "test-epub/OEBPS"
HTML Tidy for Linux version 5.6.0
Tidy ncx 0
Tidy opf 0
test-epub/mimetype
Pack mimetype 0
Pack metadir 0
Pack outputdir 0
Copy generated epub 
Copy: cp "test-epub/test.epub" "test.epub"
```

Contents of ```svg-inkscape/```:
```
glider_svg-raw.pdf  glider_svg-tex.pdf  glider_svg-tex.pdf_tex
```

**Comment by michal-h21** [comment]
It seems like the `png` haven't been created. Do you have actual `tex4ht` instalation? (Like TeX Live 2018). You should see something like the following message near the end of compilation:

```
System call: rungs -q -dNOPAUSE -dBATCH -sDEVICE=pngalpha -r300 -dFirstPage='1' -dLastPage='1' -sOutputFile='./svg-inkscape/glider_svg-tex-1.png' ./svg-inkscape/glider_svg-tex.pdf
```

**Comment by DavidGriffith** [comment]
Regarding the bug in tex4ht, I can't grok that source well enough to identify the problem.  Would you please file a report for it at https://puszcza.gnu.org.ua/bugs/?group=tex4ht ?

**Comment by michal-h21** [comment]
@DavidGriffith the XeTeX issue was already solved in `tex4ht`, it is included in updated TeX Live.

The `rungs` call should be executed outside LaTeX, so it won't be included in the .log file. It should be printed at the command line output of `tex4ebook`

**Comment by DavidGriffith** [comment]
Okay, here's the output captured from stdout and stderr:

```
Execute script `test.lg'
Make4ht: t4ht  "test.dvi"
----------------------------
t4ht.c (2018-06-28-11:26 kpathsea)
t4ht test.dvi 
(/usr/share/texlive/texmf-dist/tex4ht/base/unix/tex4ht.env)
Entering test.lg
Entering test.css
Entering test.tmp
System call: rungs -q -dNOPAUSE -dBATCH -sDEVICE=pngalpha -r300 -dFirstPage='1' -dLastPage='1' -sOutputFile='./svg-inkscape/glider_svg-tex-1.png' ./svg-inkscape/glider_svg-tex.pdf
sh: 1: rungs: not found
--- Warning --- System return: 32512
Parse LG
-------------------
Copy: cp "test.html" "test-epub/OEBPS"
Copy: cp "test.css" "test-epub/OEBPS"
Mimetype for tmp is not registered
Copy: cp "test.ncx" "test-epub/OEBPS"
Mimetype for opf is not registered
Mimetype for opf is not registered
Copy: cp "./svg-inkscape/glider_svg-tex-1.png" "test-epub/OEBPS/./svg-inkscape"
cp: cannot stat './svg-inkscape/glider_svg-tex-1.png': No such file or directory
Copy: cp "content.opf" "test-epub/OEBPS"
HTML Tidy for Linux version 5.6.0
Tidy ncx 0
Tidy opf 0
test-epub/mimetype
Pack mimetype 0
Pack metadir 0
Pack outputdir 0
Copy generated epub 
Copy: cp "test-epub/test.epub" "test.epub"
```

**Comment by DavidGriffith** [comment]
This test document works to get an SVG into an EPUB without converting it:
```
\documentclass[\ifdefined\HCode dvips\fi]{article}
\usepackage{graphicx}
\parindent=0pt

\DeclareGraphicsExtensions{.png,.svg}
\begin{document}
Hello world!\\
%\includesvg{glider}\\
\includegraphics{glider}\\
\includegraphics{larry}
Wasn't that fun?
\end{document}
```

**Comment by DavidGriffith** [comment]
> @DavidGriffith the XeTeX issue was already solved in `tex4ht`, it is included in updated TeX Live.

How do I get this besides waiting for Debian to update to TeX Live 2019 in January or whenever?

**Comment by michal-h21** [comment]
It is already in the TL 2018, which is updated regularly in Debian, I think. Personally, I use the TL distribution from TUG, which is the most actual. But it needs to be updated separately from your Linux distro package system, so it have some cons.

I can see that `rungs` command is not present on your system, in this case you can use correct GhostScript executable name in this configuration: `\Configure{Ghostscript}{name of the command}`.

Anyway, it is best to just include the original SVG with `\includesvg`, I don't know why it didn't come to my mind earlier :). There is a issue, we already have `svg.4ht` file, which takes care of SVG images, but it is not related to the `svg.sty` package. We will have to resolve this conflict in `tex4ht`. In the meantime, the following configuration should work:

```
\Preamble{xhtml}
\DeclareGraphicsExtensions{.svg,.png,.jpg,.gif}
\renewcommand\includesvg[2][]{\includegraphics{#2}}
\begin{document}
\EndPreamble

```

**Comment by michal-h21** [comment]
`rungs` is included in TL in order to provide stable Ghostscript binary on both Unix-like and Windows systems, I think. Miktex provides it's own Ghostscript version under different name. The issue is that we cannot easily test for for a command existence from LaTeX run, so the most common value, which is `rungs` for TL is used. 

Anyway, I just resolved the name conflict with the `svg` package in `tex4ht` sources and pushed modified version of the macro I provided earlier, which includes the SVG file without unnecessary conversion step.

**Comment by DavidGriffith** [comment]
I'm revisiting my ongoing book project and it looks like things are working now.  I'll revise https://github.com/DavidGriffith/tex4ebook-demo shortly.  There are still ongoing problems with epubcheck throwing zillions of error messages.  I'll file an issue on that once I have the tex4ebook-demo repo updated to demonstrate them.

**Comment by byteptr** [comment]
We are in the end of 2023 and the problem with svg package still persists.

**Comment by michal-h21** [comment]
What problem do you have? The original MWE from this question works fine in TeX Live 2023.
