### ISSUE TITLE
assorted  ligatures replaced with 0x00

### ISSUE THREAD

**Issue by DavidGriffith** [michal-h21/tex4ebook#57]
Metadata is being mangled by something that is stripping out substrings that often are rendered as ligatures.  For instance, "ff" and "fi".  I noticed this when running an epub through ````kindlegen```` that my last name was mangled as "Grith".  

So, I put this into my source file: ````\author{David Griffith AffA BfiB}```` and got this in ````OEBPS/content.opf````:

````
<dc:creator>David Grith AA BB</dc:creator>
````

I suspect this might be related to earlier trouble I was having with  ````tex4ht```` with ligatures being turned into ````0x00```` which we discussed at https://tex.stackexchange.com/questions/458758/htlatex-garamond-fonts-and-nulled-ff-and-fi-strings .

**Comment by DavidGriffith** [comment]
Looking closer, I see that the strings (including "th", "ft", "ff", and "fi" among others) were replaced with 0x00 throughout the document.

**Comment by DavidGriffith** [comment]
More followup: I was under the impression that the business with ````makehtf.lua```` on the above StackExchange page was incorporated into tex4ebook.

**Comment by michal-h21** [comment]
It wasn't yet, but it should be soon :)
