### ISSUE TITLE
How to convert tex with Chinese characters?

### ISSUE THREAD

**Issue by ajeecai** [michal-h21/tex4ebook#59]
Hi, 
I have some tex source with contains Chinese characters, then under MacOSX, using TexShop with XeLatex typeset, it could output pdf with correct Chinese display. But in the same MacOSX, with "tex4ebook -x my.tex", the output epub lose all Chinese words , only English words in the book. 

Any ideas? 
Thanks

**Comment by michal-h21** [comment]
Try this configuration file:


```
\Preamble{xhtml}
\xeuniuseblock{CJK}
\begin{document}
\EndPreamble
```

It can be requested using the `-c` option for `tex4ebook`

**Comment by ajeecai** [comment]
really cool! It works, thanks
