### ISSUE TITLE
TOC formatting being ignored

### ISSUE THREAD

**Issue by andreashappe** [michal-h21/tex4ebook#60]
Tex4ebook seems to work almost perfectly for my book-class LaTex document.. there seems to be an issue with the included table of content: the indentation steps seem to be way to large, creating a very unstable looking TOC.

I tried to fix this in latex itself (by changing the style of the TOC) but this does not seem to be taken over to the mobi ebook. I thought that I might use the Preamble and CSS to reduce (or remove) the indentation for subsections but with the documentation split up betwen tex4ht and tex4ebook I wasn't able to find a good solution. Any suggestion?

This problem might arise more often, so I thought that I add a github issue for documentation purposes.

**Comment by michal-h21** [comment]
The TOC formatting depends on the output file format. For ePub and Mobi it is the same as in the normal `tex4ht` mode:

```
 <div class="tableofcontents">
   <span class="sectionToc" >1 <a 
href="xxxse1.html#x3-20001" id="QQ2-3-2">ahoj</a></span>
<br />    <span class="subsectionToc" >1.1 <a 
href="xxxse1.html#x3-30001.1" id="QQ2-3-3">svete</a></span>
<br />    <span class="subsectionToc" >1.2 <a 
href="xxxse1.html#x3-40001.2" id="QQ2-3-4">xxx</a></span>
<br />   <span class="sectionToc" >2 <a 
href="xxxse2.html#x4-50002" id="QQ2-4-5">dalsi</a></span>
<br />    <span class="subsectionToc" >2.1 <a 
href="xxxse2.html#x4-60002.1" id="QQ2-4-6">aaa</a></span>
   </div>
```

I don't see too big indentation in this case, but it is possible to style the `span.sectionToc` and `span.subsectionToc` elements in the CSS. 

In ePub3, the code is different, because the format requires ebook to contain TOC in the following format:

```
 <nav id="toc" epub:type="toc"> 
<ol>                          <li>  1<a 
href="xxxse1.xhtml#x3-20001" id="QQ2-3-2">ahoj</a><ol> 
       <li>  1.1<a 
href="xxxse1.xhtml#x3-30001.1" id="QQ2-3-3">svete</a><ol> 
  </ol></li>     <li>  1.2<a 
href="xxxse1.xhtml#x3-40001.2" id="QQ2-3-4">xxx</a><ol> 
  </ol></li></ol></li>     <li>  2<a 
href="xxxse2.xhtml#x4-50002" id="QQ2-4-5">dalsi</a><ol> 
       <li>  2.1<a 
href="xxxse2.xhtml#x4-60002.1" id="QQ2-4-6">aaa</a><ol> 

   </ol></li></ol></li> </ol></nav>
```

It can be again styled using CSS.

One thing I am not sure how well will work is whether the CSS will work for Mobi.

If CSS doesn't work, it is possible to modify the HTML code generated for TOC, the used configurations are documented [here](https://tug.org/applications/tex4ht/mn14.html#mn14-3).

**Comment by andreashappe** [comment]
hm, just to make sure I am doing the right thing (cause it does not seem to work):

~~~ latex
\Preamble{html}
\begin{document}
        \Css { span.sectionToc {
                        margin-left: 0em;
                }
        }
\EndPreamble
~~~

I am creating the book with `tex4ebook -s -f mobi ebook.tex`

**Comment by michal-h21** [comment]
There is one issue with your `.cfg` file, you should use `\Preamble{xhtml}`, otherwise you will produce HTML 4.0 document, which isn't really good.
I've created Lua filter that will process the table of contents, remove unnecessary white space, remove the `<br>` elements and change the `<span>` elements to `<div>`, which enables you to set margins on them:

```
local domfilter = require "make4ht-domfilter"

local process = domfilter {function(dom)
  -- process table of contents and remove unnecessary white space and <br> tags
  for _, toc in ipairs(dom:query_selector(".tableofcontents")) do
    for _, child in ipairs(toc:get_children()) do
      if child:is_text() then
        -- replace all whitespace with linebreaks
        child._text = "\n"
      elseif child:is_element() then
        local name = child:get_element_name()
        -- remove <br> elements
        if name == "br" then
          child:remove_node()
        -- change spans to divs
        elseif name == "span" then
          child._name = "div"
        end
      end
    end

  end
  
return dom
end}

Make:match("html$", process)

```

Save this file as `build.mk4` and require it using

    tex4ebook -s -f mobi -e build.mk4 ebook.tex

**Comment by andreashappe** [comment]
hm, your script works (now I see the divs), but the TOC still looks the same.

What I am duing by now is

~~~ shell
tex4ebook -s -c tex4ebook.cfg -f mobi -e build.mk4 ebook.tex
~~~

with a config file of

~~~
\Preamble{xhtml}
\begin{document}
        \Css { .sectionToc {
                        margin-left: 0em;
                }
        }
\EndPreamble
~~~

**Comment by michal-h21** [comment]
It is strange, it should be on the same indentation level now. Can you post a `mwe` of your TeX file?

**Comment by andreashappe** [comment]
do you have a gitlab.com account? currently the repository is private but I could give you access. Otherwise I can mail you an archive with the sources (not sure to which email address though)

**Comment by michal-h21** [comment]
Sure, I am michal.h21 on gitlab, so feel free to give me the access.

**Comment by andreashappe** [comment]
done

**Comment by michal-h21** [comment]
Thanks. It seems the configuration for the Book class add some indenting. It can be removed using the following build file:

```
local domfilter = require "make4ht-domfilter"
local filter = require "make4ht-filter"

local process = domfilter {function(dom)
  -- process table of contents and remove unnecessary white space and <br> tags
  for _, toc in ipairs(dom:query_selector(".tableofcontents")) do
    for _, child in ipairs(toc:get_children()) do
      if child:is_text() then
        -- replace all whitespace with linebreaks
        child._text = "\n"
      elseif child:is_element() then
        local name = child:get_element_name()
        -- remove <br> elements
        if name == "br" then
          child:remove_node()
        -- change spans to divs
        elseif name == "span" then
          child._name = "div"
        end
      end
    end

  end
  
return dom
end}

local cssprocess = filter(function(s)
   local s = s:gsub("sectionToc {margin%-left%:.em;}","sectionToc {margin-left:0em;}")
   return s
end)



Make:match("html$", process)
Make:match("css$", cssprocess)

```

**Comment by andreashappe** [comment]
worked perfectly! I've now removed the Preamble (config file) as it is not needed anymore. Thanks!
