### ISSUE TITLE
Starred captions aren't handled properly

### ISSUE THREAD

**Issue by JeanOlivier** [michal-h21/tex4ebook#63]
> OS: Ubuntu 18.04.3 LTS
> pdfTeX: 3.14159265-2.6-1.40.20 (TeX Live 2019)
> tex4ebook: v0.2c
> make4ht: v0.2g.

Consider the following snippet, compiled as epub2:
``` latex
\begin{figure}[htb]
    \begin{center}
        \includegraphics{something.pdf} 
        \caption{Short description.}
        \label{fig:figure_label}
        \caption*{More details in a longer description that won't appear in the list of figures.}
    \end{center}
\end{figure}
```
The first caption will work as intended, but the second will generate a Figure number and appear in the list of figures as e.g. "Figure 2: *", whereas it should solely add the text under the main caption.

This is fixable user-side by doing `\caption[Short description.]{Short description. More details in a longer description that won't appear in the list of figures.}` or with `\newcommand{\longcaption}[2]{\caption[#1]{#1 #2}}` but it's cumbersome and is a different behaviour than regular pdflatex. 

It could also be a problem for lonesome `\caption*` that wouldn't benefit from the above workarounds.

**Comment by michal-h21** [comment]
Sorry for the late reply. I somehow missed your post. I am now browsing older issues and found it. I think that this issue had been fixed in the meantime, starred captions aren't included in the list of figures now.
