### ISSUE TITLE
epubcheck error associated with \Configure{UniqueIdentifier} processing.

### ISSUE THREAD

**Issue by DavidGriffith** [michal-h21/tex4ebook#67]
While working over your suggestions at https://tex.stackexchange.com/questions/525098/rewriting-makechapterhead-to-include-stuff-on-previous-page/, I noticed what appears to be a problem with how tex4ebook processes `\Configure{UniqueIdentifier}`.   For the test config file, I had this line:
````
\Configure{UniqueIdentifier}{Foo Bar Press}
````
`epubcheck` complained like this:
````
Validating using EPUB version 2.0.1 rules.
ERROR(NCX-001): test.epub/OEBPS/test.ncx(-1,-1): NCX identifier ('Foo Bar Press') does not match OPF identifier ('Foo Bar Press').

Check finished with errors
Messages: 0 fatal / 1 errors / 0 warnings / 0 info

epubcheck completed
````
Looking at `test-epub/OEBPS/content.opf`, I see this:
````
    <dc:identifier id="dcidid" opf:scheme="URI">Foo Bar
    Press</dc:identifier>
````
Now this in `test-epub/OEBPS/test.ncx`
````
<meta name="dtb:uid" content="Foo Bar Press" />
````
If I replace those spaces with underscores, this complaint does not appear.
It seems to me that `tex4ebook` is improperly converting the space between `Bar` and `Press` into a newline when writing `content.opf`, which then triggers `epubcheck`.

**Comment by michal-h21** [comment]
The unique identifier should be URL, so the correct value would be something like `https://foobarpress.com/bookurl`.
