### ISSUE TITLE
Embedding fonts

### ISSUE THREAD

**Issue by DavidGriffith** [michal-h21/tex4ebook#71]
This issue is for discussion of how one might embed fonts into an EPUB file or any of the other ebook formats supported by tex4ebook.

So far, I've figured out how to directly embed fonts into an SVG file.  This is important because my cover and title page are actually SVG images.  I could convert them into PNG files, but I'd rather not and would prefer to help expand tex4ebook's capabilities.  It's not clear to me if and how tex4ebook may currently support fonts as a resource within an EPUB.  See https://www.datalogics.com/blog/ebooks/embedding-a-font-into-an-epub-file/ for what I mean.  This would be preferable to putting fonts directly into SVGs because to put them in directly means adding the font multiple times for each SVG.  Also, it's unclear how to use alternative fonts in the main body of the text.

**Comment by michal-h21** [comment]
Regarding fonts, the big question is if the reading systems support embedded fonts at all. Some of them don't support them even for HTML, I would be surprised if they supported fonts included in EPUB for SVG. 

Anyway, you can include fonts using [this package](https://github.com/michal-h21/helpers4ht/blob/master/addfont4ht.sty). It can be used in the `.cfg` file like this:
```

\RequirePackage{addfont4ht}
\Preamble{xhtml}
\SetFontFamily{EBGaramond}
\NormalFont{EBGaramond}{EBGaramond-Regular.woff}
\BoldFont{EBGaramond}{EBGaramond-Italic.woff}
\ItalicFont{EBGaramond}{EBGaramond-Italic.woff}
\Css{body{font-family:"EBGaramond", serif;}}
\begin{document}
\EndPreamble
```
This seems to work with Calibre.

**Comment by DavidGriffith** [comment]
I seem to be making some progress with this.  Thanks.
