### ISSUE TITLE
Excessive blank pages

### ISSUE THREAD

**Issue by DavidGriffith** [michal-h21/tex4ebook#73]
With this setup, there is one unwanted blank page inserted between the cover image and the title page image.  The title, dedication, and author pages are one right after the other.  After this, there are three or four unwanted blank pages before the table of contents.

Build with `tex4ebook -xs -f epub3 -c test.cfg test.tex`

````
% test.tex
\documentclass[12pt]{book}
\usepackage{graphicx}
\usepackage{lipsum}
\title{Bad Cover}
\author{David Griffith}
\begin{document}
\coverimage{cover.png}
\includegraphics[keepaspectratio=true,height=0.75\textheight]{test1.png} % title page
\includegraphics[keepaspectratio=true,height=0.75\textheight]{test2.png} % dedication
\includegraphics[keepaspectratio=true,height=0.75\textheight]{test3.png} % author
\tableofcontents
\chapter{Hello}
\lipsum[1]
\chapter{Goodbye}
\lipsum[1]
\chapter{Hello Again}
\lipsum[1]
\chapter{Whee!}
\lipsum[1]
\end{document}
````

````
% test.cfg
\Preamble{xhtml}
\Configure{UniqueIdentifier}{661.org}
\DeclareGraphicsExtensions{.svg,.png,.jpg,.gif}
\begin{document}
\EndPreamble
````

**Comment by DavidGriffith** [comment]
I think this is due to a bug in Calibre.

**Comment by michal-h21** [comment]
Sorry for not looking at this. I am currently at my vacation, so I am reacting slowly than normally. Calibre is unfortunately broke on my machine due to some Python libraries clash, so I cannot investigate it more.
