### ISSUE TITLE
Add support for .azw and .azw3 files

### ISSUE THREAD

**Issue by DavidGriffith** [michal-h21/tex4ebook#74]
Given that `kindlegen` supports output for `.azw` and `.azw3` formats and that `tex4ebook` uses `kindlegen` to make `.mobi` files, it seems fitting that support for these two other formats should be done.  I've been trying to add this myself, but am not terribly up on Lua programming, so I have this error.

````
Info(prcgen):I1036: Mobi file built successfully
cp: cannot stat 'badcover-azw/badcover.azw': No such file or directory
[STATUS]  tex4ebook: Conversion finished
````

Here's my new `tex4ebook-exec_azw.lua` file:
````
module(...,package.seeall)
local eb = require("tex4ebook-exec_epub")
local ebookutils = require("mkutils")
local log = logging.new "exec_azw"

function prepare(params)
	return eb.prepare(params)
end

function run(out,params)
	return eb.run(out, params)
end

function writeContainer()
	local ret =  eb.writeContainer()
  -- convert the epub file to azw
  local epubpath = eb.basedir .. "/" .. eb.outputfile
	log:info("Pack azw "..os.execute("kindlegen " .. epubpath))

  -- find the azw filename 
  local azwfile = epubpath:gsub("epub$", "azw")
  local azwdist = eb.destdir ..  eb.outputfile:gsub("epub$", "azw")
  -- copy the azw file to the destination directory
  -- the destination directory will be created by the epub writer, so it is possible to use
  -- the cp function which doesn't try to create directory
  ebookutils.cp(azwfile, azwdist)

	return ret
end

function clean()
	return eb.clean()
end
````

**Comment by michal-h21** [comment]
This is actually quite good start. I've fixed few things and added this + azw3 version to tex4ebook sources. It is necessary to pass the `-o ` option to kindlegen, with correct filename for the generated azw file.

I am not sure how the generated file differs except the file name, as the output from Kindlegen seems in all cases the same.

**Comment by wojciechmyszka** [comment]
On the other hand amazon has just removed kindlegen from his pages: [Here is the anouncment](https://www.amazon.com/gp/feature.html?ie=UTF8&docId=1000765211)

**Comment by michal-h21** [comment]
@wojciechmyszka I know :/ I just don't know how is the best tool to use instead of Kindlegen. Probably Calibre's `ebook-convert` , but it is currently broken on my machine because of some Python dependencies, so I cannot test it. But it is something that really needs to be fixed in the next release.
