### ISSUE TITLE
tex4ebook is deleting text

### ISSUE THREAD

**Issue by kattivizzima** [michal-h21/tex4ebook#75]
Hello,
this is the funny thing:

I write a simple text, then use tex4ebook and the content got changed (both in epub and mobi). As I can see, all the words that contains "fi" or "fl"  got changed

fluido --> uido
filo --> lo
fiato --> ato
superficie --> supercie

What can I do to avoid such behaviour?
Thank you.

**Comment by kattivizzima** [comment]
...and "ff" becomes a simple "f".
The more I read the result of the transformation, the more weird substitution I find.

I am sure there is a bunch of regexp somewhere I need to deactivate. I just need to know where to act.

Thank you.

**Comment by michal-h21** [comment]
Hi, this is probably because of ligatures in fonts used in your document.
What fonts do you use?

Dne ne 2. srp 2020 16:44 uživatel kattivizzima <notifications@github.com>
napsal:

**Comment by kattivizzima** [comment]
Thank you for answering.
I use ebgaramond, 12pt. BUT if I compile the text with 
latex FILENAME.tex 
everything works fine, no strange text replacement takes place.
That is the reason I was thinking to some regexp work gone wild.

Maybe my version is too old? 

kat@anubi:~/Scritti/pan-terr$ tex4ebook -v
tex4ebook version 0.1d

Thank you for reading.

**Comment by michal-h21** [comment]
Each font has special configuration file that contains mapping between
fontncharacters and Unicode in TeX4ht. Sometimes the mappings can be wrong
and some characters are not converted correctly. This happens usually with
ligatures such as fi. I will try to fix this, but I am on vacation without
computer now, so it will take some time. Meanwhile, you can try to use
different font for compilation with TeX4ebook, for example Latin modern.



Dne ne 2. srp 2020 21:39 uživatel kattivizzima <notifications@github.com>
napsal:

**Comment by kattivizzima** [comment]
Thank you!!
The workaround worked!

I wish you a great vacation!

kat
