### ISSUE TITLE
tex4ebook-exec_epub.lua:105: attempt to index a nil value (local 'm')

### ISSUE THREAD

**Issue by AnalyticTeh** [michal-h21/tex4ebook#77]
Hi. The following message appeared when I ran tex4ebook on Windows10:

------------------------------------------------------------

D:\>tex4ebook abc.tex
[STATUS]  tex4ebook: Conversion started
[STATUS]  tex4ebook: Input file: abc.tex
...s/MiKTeX 2.9/tex/latex/tex4ebook/tex4ebook-exec_epub.lua:105: attempt to index a nil value (local 'm')

D:\>

-------------------------------------------------------------

The following is the code of tex4ebook-exec_epub.lua from line 98 to 113.

--------------------------------------------------------------

function run(out,params)
	--local currentdir=
	outputfilename=out
	outputfile = outputfilename..".epub"
	log:info("Output file: "..outputfile)
	--lfs.chdir(metadir)
	local m= io.open(metadir.."/container.xml","w")
	m:write([[
<?xml version="1.0"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
<rootfiles>
<rootfile full-path="OEBPS/content.opf"
media-type="application/oebps-package+xml"/>
</rootfiles>
</container>
	]])

------------------------------------------------------------------

I use miktex and has upgraded the tex4ebook package to the newest version (2020-11-07)
I am not familiar with coding. Could you tell me how to correct the error?
Thank you.

**Comment by michal-h21** [comment]
This seems like it is not possible to open the metadata file on your system. Could you please try to add the following commands:

        print("Opening: " .. metadir .. "/container.xml")
        print(m, msg)

Put them jut before

	m:write([[

It should print some information just before you get the error message. On my system it prints:

      Opening: sample-epub/META-INF/container.xml
      file (0x374fa70)        nil

I expect that the second one will print `nil     some error message` for you.

Most likely, it will be a permission issue, or something similar.

**Comment by AnalyticTeh** [comment]
Hi. The two lines were added to the file tex4ebook-exec_epub.lua

________________________________________________________________

function run(out,params)
	--local currentdir=
	outputfilename=out
	outputfile = outputfilename..".epub"
	log:info("Output file: "..outputfile)
	--lfs.chdir(metadir)
	local m= io.open(metadir.."/container.xml","w")
	print("Opening: " .. metadir .. "/container.xml")
        print(m, msg)
	m:write([[

________________________________________________________________

and I got the following message:

D:\>tex4ebook abc.tex
[STATUS]  tex4ebook: Conversion started
[STATUS]  tex4ebook: Input file: abc.tex
Opening: abc-epub/META-INF/container.xml
nil     nil
...s/MiKTeX 2.9/tex/latex/tex4ebook/tex4ebook-exec_epub.lua:107: attempt to index a nil value (local 'm')

D:\>

-----------------------------------------------------------------

Thanks for your help in solving this problem.

**Comment by michal-h21** [comment]
Ah, I hoped that the second `nil` would be some usable error message instead. Anyway, it seems you run the example directly from the `D:` drive. Maybe try to create a subdirectory and execute it here?

Another thing to try is to change 

      local m= io.open(metadir.."/container.xml","w")

to 

      local m= io.open(metadir.."\\container.xml","w")

**Comment by AnalyticTeh** [comment]
Dear Michal , 
It works! 
Thank you so much!

**Comment by michal-h21** [comment]
@AnalyticTeh what fixed the issue? To work in other directory, or to change the forward slash to back slash? I would need to fix the source code if the issue was with slashes :)

**Comment by AnalyticTeh** [comment]
I followed your instruction to create a subdirectory and ran tex4ebook there and it worked. I just checked your second method, but it doesn't work. 
Thanks again.
