### ISSUE TITLE
Incompatibility with translations package due to DeclareLanguage macro

### ISSUE THREAD

**Issue by mkuron** [michal-h21/tex4ebook#78]
tex4ebook [declares a `\DeclareLanguage` macro](https://github.com/michal-h21/tex4ebook/blob/5e5fbe0a00c49d32bbfcf4362e035ed886f4826b/tex4ebook.sty#L14-L16). The _translations_ package [does too](https://github.com/cgnieder/translations/blob/cfa6a8fd77bb2d670f7e6fa30ddaaef3f43b0642/translations.sty#L142-L143), so tex4ebook is incompatible with it. Same goes for anything that depends on _translations_, such as _siunitx_.

Minimal example:
```latex
\documentclass{article}
\usepackage{siunitx}
\begin{document}
a
\end{document}
```
Build with:
```bash
tex4ebook test.tex
```
Result:
```
[ERROR]   htlatex: /usr/local/texlive/2021/texmf-dist/tex/latex/translations/translations.sty	143	 LaTeX Error: Command \DeclareLanguage already defined.
[ERROR]   htlatex: /usr/local/texlive/2021/texmf-dist/tex/latex/translations/translations.sty	806	 LaTeX Error: Missing \begin{document}.
[ERROR]   htlatex: /usr/local/texlive/2021/texmf-dist/tex/latex/translations/translations.sty	811	 LaTeX Error: Missing \begin{document}.
[ERROR]   htlatex: /usr/local/texlive/2021/texmf-dist/tex/latex/translations/translations.sty	892	 Paragraph ended before \DeclareLanguage was complete.
```

Workaround:
```bash
sed -i s/DeclareLanguage/DeclareLanguageEbook/g $(kpsewhich tex4ebook.sty)
```
It doesn't seem to me like `\DeclareLanguage` is meant for external use, so it appears to be safe to simply change its name. The same macro also exists in [rfclang.sty](https://github.com/michal-h21/helpers4ht/blob/224493fca7df34b6f589c7236dcddc8220e4e04d/rfclang.sty#L5-L7) and [rfclanguages.sty](https://github.com/michal-h21/jekyll4ht/blob/fba3fa553ef75d8b3c502f9d6b640d91d216811f/rfclanguages.sty#L4-L6) though.

**Comment by michal-h21** [comment]
You are right, it seems there is a collision with other packages. Thanks for the report. I've fixed that in `tex4ebook` sources. `TeX4ht` uses similar macro, but within it's private namespace, so it doesn't collide with other packages. Regarding `rfclang.sty` and `jekyll4ht`, these were obsoleted by TeX4ht core, so it shouldn't be that big issue.

**Comment by mkuron** [comment]
Thanks, that solves it for me.

6d2c0c8976d5a664efbc3796281cd5573bf7a20f

**Comment by olifre** [comment]
Many thanks for this fix! I've run into the same issue just now, using the most recent packages in TeXlive; would it be possible to get a new release on CTAN incorporating the fix? 
Thanks in advance!

**Comment by michal-h21** [comment]
@olifre I've uploaded the new release to CTAN today, so it should be in TL soon.

**Comment by olifre** [comment]
@michal-h21 Many thanks, I can confirm it has arrived on CTAN. Since I use it via https://github.com/xu-cheng/texlive-action I had to await the monthly rebuild of https://github.com/xu-cheng/latex-docker and can now confirm it works like a charm :+1: .
