### ISSUE TITLE
Installation issue. 

### ISSUE THREAD

**Issue by joereddington** [michal-h21/tex4ebook#83]
I've got an AWS instance and I've installed latex as follows: 

`sudo yum install texlive-pdftex texlive-latex-bin texlive-texconfig* texlive-latex* texlive-metafont* texlive-cmap* texlive-ec texlive-fncychap* texlive-pdftex-def texlive-fancyhdr* texlive-titlesec* texlive-multirow texlive-framed* texlive-wrapfig* texlive-parskip* texlive-caption texlive-ifluatex* texlive-collection-fontsrecommended texlive-collection-latexrecommended`

That works, but 'tex4ebook' isn't included.   I understand it's in texlive, because [the INSTALL.md](https://github.com/michal-h21/tex4ebook/blob/master/INSTALL.md) says so.  So it should be a simple matter of working out which package tex4ebook to use. 

https://trac.macports.org/wiki/TeXLivePackages says it's in texlive-bin-extra  
https://packages.debian.org/sid/texlive-extra-utils says it's in texlive-extra-utils 

But neither of those packages exist for me.  

Can anyone tell me which texlive package I install to access this wonderful bit of software?

**Comment by michal-h21** [comment]
I am not sure what packages are needed in this case. I can see that you use Yum, which means RPM based distro. I've found that there are these packages in Fedora: `texlive-tex4ebook`, `texlive-tex4ht` and `texlive-make4ht`. I think you will need at least these, if your distro use the same packages as Fedora.

**Comment by joereddington** [comment]
Unfortunately, of those, it appears that only sudo yum install texlive-tex4ht works (but not quite enough).  This might be better as a SE question then I think?

**Comment by michal-h21** [comment]
I think this really depends on the distribution you use, as every Linux distro can use different way how to pack TeX Live. So it may be even best to ask on a support forum for your distro. 

Personally, I use Github Actions for compilation of some of my projects (see https://github.com/michal-h21/testblog for example), and I've found that it is easiest to use full TeX Live in the container, because it is quite hard to track dependencies in the case of failure.

**Comment by joereddington** [comment]
In the end I installed from scratch using the texlive site - took a couple of hours but I now have a nice executable tex4ebook file.
