### ISSUE TITLE
Space missing in the caption (of figure)

### ISSUE THREAD

**Issue by FredericVivien** [michal-h21/tex4ebook#88]
Hi Michal

The test displayed for a caption is ``Figure 1:testofcaption'' instead of ``Figure 1: testofcaption''. In other words a spacing is missing after the semi-colon. MWE:
\documentclass{article}
\usepackage{tex4ebook}
\begin{document}
\begin{figure}
  The figure
  \caption{Some text.}
\end{figure}
\end{document}

Frédéric

**Comment by michal-h21** [comment]
Hi Frédéric,

thanks for the report. You are right, the space is missing. I will fix it in TeX4ht sources.
In the meantime, try this configuration file:

```
\Preamble{xhtml}
\catcode`\:=11
\Configure{caption}{\:xhtml{\IgnorePar\EndP}\HCode{<figcaption class="caption" ><span class="id">}}
   {:\ } {\HCode{</span><span \Hnewline class="content">}}
   {\HCode{</span></figcaption>}\HCode{<!--tex4ht:label?:
   \cur:th\:currentlabel\space-->}%
}
\catcode`\:=12
\begin{document}
\EndPreamble
```

**Comment by FredericVivien** [comment]
Hi Michal

I did not try your configuration file, but your fix in TeX4HT did the trick. Thank you.

Frédéric
