### ISSUE TITLE
Problem when interpreting hrule

### ISSUE THREAD

**Issue by FredericVivien** [michal-h21/tex4ebook#89]
Hi Michal

I am not 100% sure of this problem. As I wanted a hrule, I followed a tip of yours found online (and created my own hrule command). The result looks fine. However, epubcheck complains. Here is the MWE and the config file:

\documentclass{article}
\usepackage{tex4ebook}
\begin{document}
\myhrule
\end{document}

\Preamble{xhtml}
\begin{document}
\def\myhrule{\HCode{<hr />}}
\EndPreamble

epucheck complains about the hr tag not being authorized where it is. It looks like epubcheck is waiting for a closing tag. The problem may be that the hr tag is enclosed in a p tag. Or, maybe, I did something wrong. (Once again, using epub3.)

Best,

Frédéric

**Comment by michal-h21** [comment]
Hi Frédéric, try this configuration:

```
\Preamble{xhtml}
\begin{document}
\def\myhrule{\ifvmode\IgnorePar\fi\EndP\HCode{<hr />}\par}
\EndPreamble
```
It closes the paragraphs before `<hr />` element, which should fix the epubcheck issue.

**Comment by FredericVivien** [comment]
Hi Michal

This does the trick. Thank you.

Frédéric
