### ISSUE TITLE
Vague resolution setting documentation

### ISSUE THREAD

**Issue by phieri** [michal-h21/tex4ebook#93]
The documentation is vague on the usage of the resolution setting and units. Must the value always be in pixels per inch (for example `120`) or can it be with a unit (for example `100ppcm`).
https://github.com/michal-h21/tex4ebook/blob/024c2911cfa806d78a883937ca50fce6aa035fd2/README.md?plain=1#L110-L113

**Comment by michal-h21** [comment]
@phieri the main issue is that the `--resolution` parameter doesn't work at all. I've updated the [documentation about build files](https://github.com/michal-h21/tex4ebook#build-files), the `Make:image()` function should be used instead.
