### ISSUE TITLE
Option --tidy makes no difference

### ISSUE THREAD

**Issue by phieri** [michal-h21/tex4ebook#96]
The command line option `--tidy` doesn't seem to make any difference. The tidy program is run at the end of compilation both with and without the option set, as far as I can tell.

**Comment by michal-h21** [comment]
Tidy runs at the end of the compilation to post-process metadata XML files, when it is installed on your system. The `--tidy` option requests tidy cleanup also for all generated HTML files. You can try the `-a debug` option to see if Tidy is executed on all files. It should print something like this to the terminal output:

       exec_epub: Tidy: epubtest.html

**Comment by michal-h21** [comment]
Ah, it can be a bit misleading. I've changed that sentence, to make it more clear.
